
Error Timestamp: 2024-02-01 18:35:26
Error Dump:
[Errno 2] No such file or directory: 'int.osx'
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = loader.loader(verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\loader.py", line 10, in loader
    with open(self.file_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'int.osx'

Error Timestamp: 2024-02-01 18:35:51
Error Dump:
[Errno 2] No such file or directory: 'int1.osx'
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = loader.loader(verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\loader.py", line 10, in loader
    with open(self.file_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'int1.osx'

Error Timestamp: 2024-02-01 18:36:19
Error Dump:
[Errno 2] No such file or directory: 'int.osx'
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = loader.loader(verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\loader.py", line 10, in loader
    with open(self.file_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'int.osx'

Error Timestamp: 2024-02-01 18:36:35
Error Dump:
[Errno 2] No such file or directory: 'int.osx'
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = loader.loader(verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\loader.py", line 10, in loader
    with open(self.file_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'int.osx'

Error Timestamp: 2024-02-01 18:37:40
Error Dump:
[Errno 2] No such file or directory: 'int.osx'
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = loader.loader(verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\loader.py", line 10, in loader
    with open(self.file_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'int.osx'

Error Timestamp: 2024-02-01 18:43:41
Error Dump:
Error: Cannot load a new program while another program is already ready to run at the same location.
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 114, in start
    self.run_command(command, args)
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 77, in run_command
    self.load_program(filename, verbose)
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 20, in load_program
    raise ProgramLoadError()
ProgramLoadError: Error: Cannot load a new program while another program is already ready to run at the same location.

Error Timestamp: 2024-02-01 18:50:19
Error Dump:
Error: Cannot load a new program while another program is already ready to run at the same location.
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 114, in start
    self.run_command(command, args)
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 77, in run_command
    self.load_program(filename, verbose)
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 20, in load_program
    raise ProgramLoadError()
ProgramLoadError: Error: Cannot load a new program while another program is already ready to run at the same location.
