
Error Timestamp: 2024-03-06 16:48:07
Error Dump:
deque index out of range
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 260, in start
    self.run_command(command, args)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 217, in run_command
    self.round_robin()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 72, in round_robin
    if self.cpus.queue[0].arrival_time <= self.registers.read('CLOCK'):
       ~~~~~~~~~~~~~~~^^^
IndexError: deque index out of range

Error Timestamp: 2024-03-06 16:49:46
Error Dump:
deque index out of range
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 260, in start
    self.run_command(command, args)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 217, in run_command
    self.round_robin()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 72, in round_robin
    if self.cpus.queue[0].arrival_time <= self.registers.read('CLOCK'):
       ~~~~~~~~~~~~~~~^^^
IndexError: deque index out of range

Error Timestamp: 2024-03-06 16:52:20
Error Dump:
Error: Cannot load a new program while another program is already ready to run at the same location.
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 28, in load_program
    b_size, first_instruction_address, loader_address = self.loader.loader(filename, verbose)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 18, in loader
    raise ProgramLoadError()
ProgramLoadError.ProgramLoadError: Error: Cannot load a new program while another program is already ready to run at the same location.

Error Timestamp: 2024-03-06 17:01:58
Error Dump:
Error: Cannot load a new program while another program is already ready to run at the same location.
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 28, in load_program
    b_size, first_instruction_address, loader_address = self.loader.loader(filename, verbose)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 18, in loader
    raise ProgramLoadError()
ProgramLoadError.ProgramLoadError: Error: Cannot load a new program while another program is already ready to run at the same location.
